/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 02 11:13:30 GMT 2026
 */

package com.bank.logic;

import org.junit.Test;
import static org.junit.Assert.*;
import com.bank.logic.InsolventException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class InsolventException_ESTest extends InsolventException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InsolventException insolventException0 = new InsolventException("t");
      assertNotNull(insolventException0);
  }
}
