/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 02 11:13:21 GMT 2026
 */

package com.bank.logic;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.bank.logic.SavingsAccount;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SavingsAccount_ESTest extends SavingsAccount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.02, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      
      String string0 = savingsAccount0.getAccountSummary();
      assertNotNull(string0);
      assertEquals("Balance: 0.00 | Transactions: 1", string0);
      assertEquals(0.02, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0, 0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      
      double double0 = savingsAccount0.getBalance();
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0, 0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      
      double double0 = savingsAccount0.getInterestRate();
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0, 0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      
      List<String> list0 = savingsAccount0.getHistory();
      assertNotNull(list0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      assertEquals(1, list0.size());
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(3113.850693275, 3113.850693275);
      assertNotNull(savingsAccount0);
      assertEquals(3113.850693275, savingsAccount0.getBalance(), 0.01);
      assertEquals(3113.850693275, savingsAccount0.getInterestRate(), 0.01);
      
      savingsAccount0.applyInterest();
      assertEquals(9699179.990702473, savingsAccount0.getBalance(), 0.01);
      assertEquals(3113.850693275, savingsAccount0.getInterestRate(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0, 0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      
      String string0 = savingsAccount0.toString();
      assertNotNull(string0);
      assertEquals("SavingsAccount{balance=0.0, interestRate=0.0}", string0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SavingsAccount savingsAccount0 = null;
      try {
        savingsAccount0 = new SavingsAccount((-372.5184));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid initial values
         //
         verifyException("com.bank.logic.SavingsAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SavingsAccount savingsAccount0 = null;
      try {
        savingsAccount0 = new SavingsAccount(2429.67746001691, (-1.0));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid initial values
         //
         verifyException("com.bank.logic.SavingsAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0, 0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      
      savingsAccount0.processTransaction(0.0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0, 0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      
      // Undeclared exception!
      try { 
        savingsAccount0.processTransaction((-1.0));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Insufficient balance: -1.0
         //
         verifyException("com.bank.logic.SavingsAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0, 0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      
      savingsAccount0.processTransaction(1.0);
      assertEquals(1.0, savingsAccount0.getBalance(), 0.01);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      
      savingsAccount0.processTransaction((-1.0));
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(0.0, 0.0);
      assertNotNull(savingsAccount0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(0.0, savingsAccount0.getBalance(), 0.01);
      
      savingsAccount0.processTransaction(1.0);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(1.0, savingsAccount0.getBalance(), 0.01);
      
      double double0 = savingsAccount0.getBalance();
      assertEquals(1.0, double0, 0.01);
      assertEquals(0.0, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(1.0, savingsAccount0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(3113.850693275, 3113.850693275);
      assertNotNull(savingsAccount0);
      assertEquals(3113.850693275, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(3113.850693275, savingsAccount0.getBalance(), 0.01);
      
      double double0 = savingsAccount0.getInterestRate();
      assertEquals(3113.850693275, double0, 0.01);
      assertEquals(3113.850693275, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(3113.850693275, savingsAccount0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount(3113.850693275, 3113.850693275);
      assertNotNull(savingsAccount0);
      assertEquals(3113.850693275, savingsAccount0.getBalance(), 0.01);
      assertEquals(3113.850693275, savingsAccount0.getInterestRate(), 0.01);
      
      savingsAccount0.processTransaction((-2230.0936685));
      assertEquals(3113.850693275, savingsAccount0.getInterestRate(), 0.01);
      assertEquals(883.757024775, savingsAccount0.getBalance(), 0.01);
  }
}
